### PR TITLE
Added loaders

### PR DESCRIPTION
**Pull request by martijnmelchers**
I think I get it now xD

### CODE REVIEW

**Review by Gilbert142 — APPROVED** [review]
Looks good, we should use this for the rest of the website aswell!

**Comment by justinoboyle** [comment]
Nothing in the src/ folder should ever be used in raw production; some browsers do not support it. This is why I created a minified and transpiled version in the js/ folder. Later today I will make a webpack script to make this process easier. Please reverse this merge, as it most likely breaks compatibility in Safari and Edge, as well as old versions of Chrome and Firefox.

**Comment by martijnmelchers** [comment]
This is now working.

**Comment by Gilbert142** [comment]
@martijnmelchers So ready to merge?

**Pull request merged**
